/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersLogSyncStatus struct {

	LastAttempted int64 `json:"last_attempted,omitempty"`

	LastException string `json:"last_exception,omitempty"`
}
