/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersAwsAvailability string

// List of ClustersAwsAvailability
const (
	SPOT_ClustersAwsAvailability ClustersAwsAvailability = "SPOT"
	ON_DEMAND_ClustersAwsAvailability ClustersAwsAvailability = "ON_DEMAND"
	SPOT_WITH_FALLBACK_ClustersAwsAvailability ClustersAwsAvailability = "SPOT_WITH_FALLBACK"
)
