/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersAwsAttributes struct {

	FirstOnDemand int32 `json:"first_on_demand,omitempty"`

	Availability *ClustersAwsAvailability `json:"availability,omitempty"`

	ZoneId string `json:"zone_id,omitempty"`

	InstanceProfileArn string `json:"instance_profile_arn,omitempty"`

	SpotBidPricePercent int32 `json:"spot_bid_price_percent,omitempty"`

	EbsVolumeType *ClustersEbsVolumeType `json:"ebs_volume_type,omitempty"`

	EbsVolumeCount int32 `json:"ebs_volume_count,omitempty"`

	EbsVolumeSize int32 `json:"ebs_volume_size,omitempty"`
}
