/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersClusterLogConfS3 struct {

	Destination string `json:"destination,omitempty"`

	Region string `json:"region,omitempty"`

	Endpoint string `json:"endpoint,omitempty"`

	EnableEncryption bool `json:"enable_encryption,omitempty"`

	EncryptionType string `json:"encryption_type,omitempty"`

	KmsKey string `json:"kms_key,omitempty"`

	CannedAcl string `json:"canned_acl,omitempty"`
}
