/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersClusterState string

// List of ClustersClusterState
const (
	PENDING_CLUSTER_STATE ClustersClusterState = "PENDING_CLUSTER_STATE"
	RUNNING_CLUSTER_STATE ClustersClusterState = "RUNNING_CLUSTER_STATE"
	RESTARTING_CLUSTER_STATE ClustersClusterState = "RESTARTING_CLUSTER_STATE"
	RESIZING_CLUSTER_STATE ClustersClusterState = "RESIZING_CLUSTER_STATE"
	TERMINATING_CLUSTER_STATE ClustersClusterState = "TERMINATING_CLUSTER_STATE"
	TERMINATED_CLUSTER_STATE ClustersClusterState = "TERMINATED_CLUSTER_STATE"
	ERROR_CLUSTER_STATE ClustersClusterState = "ERROR_CLUSTER_STATE"
	UNKNOWN_CLUSTER_STATE ClustersClusterState = "UNKNOWN_CLUSTER_STATE"
)
