/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersEbsVolumeType string

// List of ClustersEbsVolumeType
const (
	GENERAL_PURPOSE_SSD_ClustersEbsVolumeType ClustersEbsVolumeType = "GENERAL_PURPOSE_SSD"
	THROUGHPUT_OPTIMIZED_HDD_ClustersEbsVolumeType ClustersEbsVolumeType = "THROUGHPUT_OPTIMIZED_HDD"
)
