/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersTerminationCode string

// List of ClustersTerminationCode
const (
	USER_REQUEST_ClustersTerminationCode ClustersTerminationCode = "USER_REQUEST"
	JOB_FINISHED_ClustersTerminationCode ClustersTerminationCode = "JOB_FINISHED"
	INACTIVITY_ClustersTerminationCode ClustersTerminationCode = "INACTIVITY"
	CLOUD_PROVIDER_SHUTDOWN_ClustersTerminationCode ClustersTerminationCode = "CLOUD_PROVIDER_SHUTDOWN"
	COMMUNICATION_LOST_ClustersTerminationCode ClustersTerminationCode = "COMMUNICATION_LOST"
	CLOUD_PROVIDER_LAUNCH_FAILURE_ClustersTerminationCode ClustersTerminationCode = "CLOUD_PROVIDER_LAUNCH_FAILURE"
	SPARK_STARTUP_FAILURE_ClustersTerminationCode ClustersTerminationCode = "SPARK_STARTUP_FAILURE"
	INVALID_ARGUMENT_ClustersTerminationCode ClustersTerminationCode = "INVALID_ARGUMENT"
	UNEXPECTED_LAUNCH_FAILURE_ClustersTerminationCode ClustersTerminationCode = "UNEXPECTED_LAUNCH_FAILURE"
	INTERNAL_ERROR_ClustersTerminationCode ClustersTerminationCode = "INTERNAL_ERROR"
	INSTANCE_UNREACHABLE_ClustersTerminationCode ClustersTerminationCode = "INSTANCE_UNREACHABLE"
	REQUEST_REJECTED_ClustersTerminationCode ClustersTerminationCode = "REQUEST_REJECTED"
)
