/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersAutoScale struct {

	MinWorkers int32 `json:"min_workers,omitempty"`

	MaxWorkers int32 `json:"max_workers,omitempty"`
}
