/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersSparkNode struct {

	PrivateIp string `json:"private_ip,omitempty"`

	PublicDns string `json:"public_dns,omitempty"`

	NodeId string `json:"node_id,omitempty"`

	InstanceId string `json:"instance_id,omitempty"`

	StartTimestamp int64 `json:"start_timestamp,omitempty"`

	HostPrivateIp string `json:"host_private_ip,omitempty"`
}
