/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClustersClusterSource string

// List of ClustersClusterSource
const (
	UI_ClustersClusterSource ClustersClusterSource = "UI"
	JOB_ClustersClusterSource ClustersClusterSource = "JOB"
	API_ClustersClusterSource ClustersClusterSource = "API"
)
