/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ClusterSpec struct {

	ExistingClusterId string `json:"existing_cluster_id,omitempty"`

	NewCluster *NewCluster `json:"new_cluster,omitempty"`

	Libraries []Library `json:"libraries,omitempty"`
}
