/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type Job struct {

	JobId int32 `json:"job_id,omitempty"`

	CreatorUserName string `json:"creator_user_name,omitempty"`

	Settings *JobSettings `json:"settings,omitempty"`

	CreatedTime int32 `json:"created_time,omitempty"`
}
