/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type JobTask struct {

	NotebookTask *NotebookTask `json:"notebook_task,omitempty"`

	SparkJarTask *SparkJarTask `json:"spark_jar_task,omitempty"`

	SparkPythonTask *SparkPythonTask `json:"spark_python_task,omitempty"`

	SparkSubmitTask *SparkSubmitTask `json:"spark_submit_task,omitempty"`
}
