/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type JobEmailNotifications struct {

	OnStart []string `json:"on_start,omitempty"`

	OnSuccess []string `json:"on_success,omitempty"`

	OnFailure []string `json:"on_failure,omitempty"`

	NoAlertForSkippedRuns bool `json:"no_alert_for_skipped_runs,omitempty"`
}
