/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type LibraryInstallStatus string

// List of LibraryInstallStatus
const (
	PENDING_LibraryInstallStatus LibraryInstallStatus = "PENDING"
	RESOLVING_LibraryInstallStatus LibraryInstallStatus = "RESOLVING"
	INSTALLING_LibraryInstallStatus LibraryInstallStatus = "INSTALLING"
	INSTALLED_LibraryInstallStatus LibraryInstallStatus = "INSTALLED"
	FAILED_LibraryInstallStatus LibraryInstallStatus = "FAILED"
	UNINSTALL_ON_RESTART_LibraryInstallStatus LibraryInstallStatus = "UNINSTALL_ON_RESTART"
)
