/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type LibraryInstallStatus string

// List of LibraryInstallStatus
const (
	PENDING_LIBRARY_STATUS LibraryInstallStatus = "PENDING_LIBRARY_STATUS"
	RESOLVING_LIBRARY_STATUS LibraryInstallStatus = "RESOLVING_LIBRARY_STATUS"
	INSTALLING_LIBRARY_STATUS LibraryInstallStatus = "INSTALLING_LIBRARY_STATUS"
	INSTALLED_LIBRARY_STATUS LibraryInstallStatus = "INSTALLED_LIBRARY_STATUS"
	FAILED_LIBRARY_STATUS LibraryInstallStatus = "FAILED_LIBRARY_STATUS"
	UNINSTALL_ON_RESTART_LIBRARY_STATUS LibraryInstallStatus = "UNINSTALL_ON_RESTART_LIBRARY_STATUS"
)
