/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type Library struct {

	Jar string `json:"jar,omitempty"`

	Egg string `json:"egg,omitempty"`

	Whl string `json:"whl,omitempty"`

	Pypi *PythonPyPiLibrary `json:"pypi,omitempty"`

	Maven *MavenLibrary `json:"maven,omitempty"`

	Cran *RCranLibrary `json:"cran,omitempty"`
}
