/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type LibraryFullStatus struct {

	Library *Library `json:"library,omitempty"`

	Status *LibraryInstallStatus `json:"status,omitempty"`

	Messages []string `json:"messages,omitempty"`

	IsLibraryForAllClusters bool `json:"is_library_for_all_clusters,omitempty"`
}
