/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type RCranLibrary struct {

	Package_ string `json:"package,omitempty"`

	Repo string `json:"repo,omitempty"`
}
