/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type Run struct {

	JobId int32 `json:"job_id,omitempty"`

	RunId int32 `json:"run_id,omitempty"`

	CreatorUserName string `json:"creator_user_name,omitempty"`

	NumberInJob int32 `json:"number_in_job,omitempty"`

	OriginalAttemptRunId int32 `json:"original_attempt_run_id,omitempty"`

	State *RunState `json:"state,omitempty"`

	Schedule *CronSchedule `json:"schedule,omitempty"`

	Task *JobTask `json:"task,omitempty"`

	ClusterSpec *ClusterSpec `json:"cluster_spec,omitempty"`

	ClusterInstance *ClusterInstance `json:"cluster_instance,omitempty"`

	OverridingParameters *RunParameters `json:"overriding_parameters,omitempty"`

	StartTime int32 `json:"start_time,omitempty"`

	SetupDuration int32 `json:"setup_duration,omitempty"`

	ExecutionDuration int32 `json:"execution_duration,omitempty"`

	CleanupDuration int32 `json:"cleanup_duration,omitempty"`

	Trigger *TriggerType `json:"trigger,omitempty"`
}
