/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type RunParameters struct {

	JarParams []string `json:"jar_params,omitempty"`

	NotebookParams []ParamPair `json:"notebook_params,omitempty"`

	PythonParams []string `json:"python_params,omitempty"`

	SparkSubmitParams []string `json:"spark_submit_params,omitempty"`
}
