/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type RunLifeCycleState string

// List of RunLifeCycleState
const (
	PENDING_RUN_STATUS RunLifeCycleState = "PENDING_RUN_STATUS"
	RUNNING_RUN_STATUS RunLifeCycleState = "RUNNING_RUN_STATUS"
	TERMINATING_RUN_STATUS RunLifeCycleState = "TERMINATING_RUN_STATUS"
	TERMINATED_RUN_STATUS RunLifeCycleState = "TERMINATED_RUN_STATUS"
	SKIPPED_RUN_STATUS RunLifeCycleState = "SKIPPED_RUN_STATUS"
	INTERNAL_ERROR_RUN_STATUS RunLifeCycleState = "INTERNAL_ERROR_RUN_STATUS"
)
