/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type RunLifeCycleState string

// List of RunLifeCycleState
const (
	PENDING_RunLifeCycleState RunLifeCycleState = "PENDING"
	RUNNING_RunLifeCycleState RunLifeCycleState = "RUNNING"
	TERMINATING_RunLifeCycleState RunLifeCycleState = "TERMINATING"
	TERMINATED_RunLifeCycleState RunLifeCycleState = "TERMINATED"
	SKIPPED_RunLifeCycleState RunLifeCycleState = "SKIPPED"
	INTERNAL_ERROR_RunLifeCycleState RunLifeCycleState = "INTERNAL_ERROR"
)
