/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type SparkPythonTask struct {

	PythonFile string `json:"python_file"`

	Parameters []string `json:"parameters,omitempty"`
}
