/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ViewsToExport string

// List of ViewsToExport
const (
	CODE_ViewsToExport ViewsToExport = "CODE"
	DASHBOARDS_ViewsToExport ViewsToExport = "DASHBOARDS"
	ALL_ViewsToExport ViewsToExport = "ALL"
)
