/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type ViewType string

// List of ViewType
const (
	NOTEBOOK_VIEW_TYPE ViewType = "NOTEBOOK_VIEW_TYPE"
	DASHBOARD_VIEW_TYPE ViewType = "DASHBOARD_VIEW_TYPE"
)
