/*
 * Databricks REST API
 *
 * The Databricks REST API 2.0 supports of a variety of services.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package databricks

type WorkspaceObjectType string

// List of WorkspaceObjectType
const (
	NOTEBOOK_OBJECT_TYPE WorkspaceObjectType = "NOTEBOOK_OBJECT_TYPE"
	DIRECTORY_OBJECT_TYPE WorkspaceObjectType = "DIRECTORY_OBJECT_TYPE"
	LIBRARY_OBJECT_TYPE WorkspaceObjectType = "LIBRARY_OBJECT_TYPE"
)
